/**
 * Mock Data — realistic test data for offline development.
 *
 * Toggle USE_MOCKS in api.ts to enable/disable.
 * When the real backend is ready, set USE_MOCKS = false.
 */

import type { User, Session, Track, RoomMode, MockUser } from '../types';

// ─── Mock User ──────────────────────────────────────────────

export const mockUser: User = {
  id: 'usr_mock_001',
  username: 'caleb',
  email: 'caleb@frequenc.app',
  avatarUrl: undefined,
  connectedServices: {
    spotify: { connected: true, username: 'calebruble' },
    appleMusic: { connected: false },
  },
  sessionsHosted: 12,
  tracksAdded: 87,
  totalListeningTime: 4320, // minutes
  voltageBalance: 340,
  createdAt: '2025-11-15T08:00:00Z',
};

// ─── Mock Sessions ──────────────────────────────────────────

export const mockSessions: Session[] = [
  {
    id: 'ses_001',
    name: 'Late Night Vibes',
    hostId: 'usr_mock_001',
    hostUsername: 'caleb',
    roomMode: 'campfire' as RoomMode,
    genre: 'Lo-fi / Chill',
    isPublic: true,
    isLive: true,
    joinCode: 'VIBE42',
    description: 'Chill beats for late night coding sessions.',
    listeners: [
      { userId: 'usr_002', username: 'maya', avatarUrl: undefined },
      { userId: 'usr_003', username: 'jordan', avatarUrl: undefined },
      { userId: 'usr_004', username: 'alex', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_001',
      title: 'Snowfall',
      artist: 'Øneheart × Reidenshi',
      albumArt: undefined,
      duration: 198,
      addedBy: { userId: 'usr_mock_001', username: 'caleb' },
      votes: 5,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-16T01:00:00Z',
  },
  {
    id: 'ses_002',
    name: 'Discover Hour',
    hostId: 'usr_005',
    hostUsername: 'priya',
    roomMode: 'spotlight' as RoomMode,
    genre: 'Indie / Alternative',
    isPublic: true,
    isLive: true,
    joinCode: 'DISC77',
    description: 'Host picks the vibe. Trust the queue.',
    listeners: [
      { userId: 'usr_006', username: 'sam', avatarUrl: undefined },
      { userId: 'usr_007', username: 'niko', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_010',
      title: 'Motion Sickness',
      artist: 'Phoebe Bridgers',
      albumArt: undefined,
      duration: 282,
      addedBy: { userId: 'usr_005', username: 'priya' },
      votes: 8,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-16T02:30:00Z',
  },
  {
    id: 'ses_003',
    name: 'Anything Goes',
    hostId: 'usr_008',
    hostUsername: 'dex',
    roomMode: 'openFloor' as RoomMode,
    genre: 'Mixed',
    isPublic: true,
    isLive: true,
    joinCode: 'FREE99',
    description: 'No rules. Add whatever. Chaos encouraged.',
    listeners: [
      { userId: 'usr_009', username: 'lina', avatarUrl: undefined },
      { userId: 'usr_010', username: 'raf', avatarUrl: undefined },
      { userId: 'usr_011', username: 'jenny', avatarUrl: undefined },
      { userId: 'usr_012', username: 'ko', avatarUrl: undefined },
      { userId: 'usr_013', username: 'miles', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_020',
      title: 'HUMBLE.',
      artist: 'Kendrick Lamar',
      albumArt: undefined,
      duration: 177,
      addedBy: { userId: 'usr_009', username: 'lina' },
      votes: 12,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-15T22:00:00Z',
  },
  {
    id: 'ses_004',
    name: 'R&B Slow Jams',
    hostId: 'usr_014',
    hostUsername: 'dani',
    roomMode: 'campfire' as RoomMode,
    genre: 'R&B / Soul',
    isPublic: true,
    isLive: true,
    joinCode: 'SOUL88',
    description: 'Smooth vocals, warm basslines. Late night R&B only.',
    listeners: [
      { userId: 'usr_015', username: 'tay', avatarUrl: undefined },
      { userId: 'usr_016', username: 'ish', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_030',
      title: 'Best Part',
      artist: 'Daniel Caesar ft. H.E.R.',
      albumArt: undefined,
      duration: 216,
      addedBy: { userId: 'usr_014', username: 'dani' },
      votes: 6,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-16T03:00:00Z',
  },
  {
    id: 'ses_005',
    name: 'Rap Caviar Live',
    hostId: 'usr_017',
    hostUsername: 'king',
    roomMode: 'openFloor' as RoomMode,
    genre: 'Hip-Hop / Rap',
    isPublic: true,
    isLive: true,
    joinCode: 'BARS55',
    description: 'Bars only. If it slaps, it stays.',
    listeners: [
      { userId: 'usr_018', username: 'ace', avatarUrl: undefined },
      { userId: 'usr_019', username: 'nova', avatarUrl: undefined },
      { userId: 'usr_020', username: 'zeke', avatarUrl: undefined },
      { userId: 'usr_021', username: 'riri', avatarUrl: undefined },
      { userId: 'usr_022', username: 'dame', avatarUrl: undefined },
      { userId: 'usr_023', username: 'juls', avatarUrl: undefined },
      { userId: 'usr_024', username: 'trev', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_031',
      title: 'Not Like Us',
      artist: 'Kendrick Lamar',
      albumArt: undefined,
      duration: 274,
      addedBy: { userId: 'usr_017', username: 'king' },
      votes: 18,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-15T21:30:00Z',
  },
  {
    id: 'ses_006',
    name: 'Sunday Morning Jazz',
    hostId: 'usr_025',
    hostUsername: 'ella',
    roomMode: 'spotlight' as RoomMode,
    genre: 'Jazz / Blues',
    isPublic: true,
    isLive: true,
    joinCode: 'JAZZ11',
    description: 'Curated jazz for a slow morning. Trust the host.',
    listeners: [
      { userId: 'usr_026', username: 'cole', avatarUrl: undefined },
      { userId: 'usr_027', username: 'mia', avatarUrl: undefined },
      { userId: 'usr_028', username: 'theo', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_032',
      title: 'Blue in Green',
      artist: 'Miles Davis',
      albumArt: undefined,
      duration: 327,
      addedBy: { userId: 'usr_025', username: 'ella' },
      votes: 4,
      source: 'spotify',
    },
    queue: [],
    createdAt: '2026-02-16T09:00:00Z',
  },
  {
    id: 'ses_007',
    name: 'EDM Pregame',
    hostId: 'usr_029',
    hostUsername: 'volt',
    roomMode: 'openFloor' as RoomMode,
    genre: 'Electronic / Dance',
    isPublic: true,
    isLive: true,
    joinCode: 'DROP33',
    description: 'Getting hyped before going out. Drop your bangers.',
    listeners: [
      { userId: 'usr_030', username: 'kai', avatarUrl: undefined },
      { userId: 'usr_031', username: 'sky', avatarUrl: undefined },
      { userId: 'usr_032', username: 'zen', avatarUrl: undefined },
      { userId: 'usr_033', username: 'riot', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_033',
      title: 'Strobe',
      artist: 'deadmau5',
      albumArt: undefined,
      duration: 637,
      addedBy: { userId: 'usr_029', username: 'volt' },
      votes: 9,
      source: 'soundcloud',
    },
    queue: [],
    createdAt: '2026-02-15T23:45:00Z',
  },
  {
    id: 'ses_008',
    name: 'Study Beats',
    hostId: 'usr_034',
    hostUsername: 'luna',
    roomMode: 'campfire' as RoomMode,
    genre: 'Lo-fi / Chill',
    isPublic: true,
    isLive: true,
    joinCode: 'CRAM22',
    description: 'Focus mode. Lo-fi, ambient, instrumentals. No lyrics.',
    listeners: [
      { userId: 'usr_035', username: 'ash', avatarUrl: undefined },
    ],
    currentTrack: {
      id: 'trk_034',
      title: 'Affection',
      artist: 'Jinsang',
      albumArt: undefined,
      duration: 152,
      addedBy: { userId: 'usr_034', username: 'luna' },
      votes: 3,
      source: 'soundcloud',
    },
    queue: [],
    createdAt: '2026-02-16T04:15:00Z',
  },
];

// ─── Mock Queue ─────────────────────────────────────────────

export const mockQueue: Track[] = [
  {
    id: 'trk_002',
    title: 'Pink + White',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 213,
    addedBy: { userId: 'usr_002', username: 'maya' },
    votes: 3,
    source: 'spotify',
  },
  {
    id: 'trk_003',
    title: 'Electric Feel',
    artist: 'MGMT',
    albumArt: undefined,
    duration: 229,
    addedBy: { userId: 'usr_003', username: 'jordan' },
    votes: 7,
    source: 'spotify',
  },
  {
    id: 'trk_004',
    title: 'Redbone',
    artist: 'Childish Gambino',
    albumArt: undefined,
    duration: 327,
    addedBy: { userId: 'usr_mock_001', username: 'caleb' },
    votes: 2,
    source: 'spotify',
  },
  {
    id: 'trk_005',
    title: 'Ivy',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 249,
    addedBy: { userId: 'usr_004', username: 'alex' },
    votes: 5,
    source: 'spotify',
  },
];

// ─── Mock Search Results ────────────────────────────────────

export const mockSearchResults: Track[] = [
  {
    id: 'search_001',
    title: 'Nights',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 306,
    addedBy: { userId: '', username: '' },
    votes: 0,
    source: 'spotify',
  },
  {
    id: 'search_002',
    title: 'Self Control',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 249,
    addedBy: { userId: '', username: '' },
    votes: 0,
    source: 'spotify',
  },
  {
    id: 'search_003',
    title: 'Nikes',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 314,
    addedBy: { userId: '', username: '' },
    votes: 0,
    source: 'spotify',
  },
  {
    id: 'search_004',
    title: 'Thinkin Bout You',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 200,
    addedBy: { userId: '', username: '' },
    votes: 0,
    source: 'spotify',
  },
  {
    id: 'search_005',
    title: 'Chanel',
    artist: 'Frank Ocean',
    albumArt: undefined,
    duration: 210,
    addedBy: { userId: '', username: '' },
    votes: 0,
    source: 'spotify',
  },
];

// ─── Mock Users (for People search) ────────────────────────

export const mockUsers: MockUser[] = [
  { id: 'usr_002', username: 'maya', avatarUrl: undefined, sessionsCount: 8, tracksAdded: 42 },
  { id: 'usr_003', username: 'jordan', avatarUrl: undefined, sessionsCount: 5, tracksAdded: 23 },
  { id: 'usr_004', username: 'alex', avatarUrl: undefined, sessionsCount: 3, tracksAdded: 15 },
  { id: 'usr_005', username: 'priya', avatarUrl: undefined, sessionsCount: 14, tracksAdded: 67 },
  { id: 'usr_006', username: 'sam', avatarUrl: undefined, sessionsCount: 2, tracksAdded: 8 },
  { id: 'usr_008', username: 'dex', avatarUrl: undefined, sessionsCount: 11, tracksAdded: 55 },
  { id: 'usr_014', username: 'dani', avatarUrl: undefined, sessionsCount: 7, tracksAdded: 31 },
  { id: 'usr_017', username: 'king', avatarUrl: undefined, sessionsCount: 9, tracksAdded: 48 },
  { id: 'usr_025', username: 'ella', avatarUrl: undefined, sessionsCount: 6, tracksAdded: 29 },
  { id: 'usr_029', username: 'volt', avatarUrl: undefined, sessionsCount: 4, tracksAdded: 19 },
  { id: 'usr_034', username: 'luna', avatarUrl: undefined, sessionsCount: 10, tracksAdded: 38 },
];

// ─── Mock API Helpers ───────────────────────────────────────

/** Simulate network delay (200–600ms) */
export function mockDelay(min = 200, max = 600): Promise<void> {
  const ms = Math.floor(Math.random() * (max - min + 1)) + min;
  return new Promise((resolve) => setTimeout(resolve, ms));
}
